[workspace]

[package]
name = "get-certificate"
version = "0.1.0"
authors = ["fortanix.com"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
em-app = { path = "../../" }
mbedtls = { version = "0.8.0", features = [ "rdrand" ] }
serde_json = "1.0"

[patch.crates-io]
rustc-serialize = { git = "https://github.com/jethrogb/rustc-serialize.git", branch = "portability" }
